/**
 * Country name → ISO 3166-1 alpha-2 → regional indicator emoji flag.
 * No external dependencies. Case-insensitive with common aliases.
 */

const COUNTRY_TO_ISO: Record<string, string> = {
  // A
  'afghanistan': 'AF',
  'albania': 'AL',
  'algeria': 'DZ',
  'andorra': 'AD',
  'angola': 'AO',
  'antigua and barbuda': 'AG',
  'argentina': 'AR',
  'armenia': 'AM',
  'australia': 'AU',
  'austria': 'AT',
  'azerbaijan': 'AZ',
  // B
  'bahamas': 'BS',
  'the bahamas': 'BS',
  'bahrain': 'BH',
  'bangladesh': 'BD',
  'barbados': 'BB',
  'belarus': 'BY',
  'belgium': 'BE',
  'belize': 'BZ',
  'benin': 'BJ',
  'bhutan': 'BT',
  'bolivia': 'BO',
  'bosnia and herzegovina': 'BA',
  'botswana': 'BW',
  'brazil': 'BR',
  'brunei': 'BN',
  'bulgaria': 'BG',
  'burkina faso': 'BF',
  'burundi': 'BI',
  // C
  'cabo verde': 'CV',
  'cape verde': 'CV',
  'cambodia': 'KH',
  'cameroon': 'CM',
  'canada': 'CA',
  'central african republic': 'CF',
  'chad': 'TD',
  'chile': 'CL',
  'china': 'CN',
  "people's republic of china": 'CN',
  'colombia': 'CO',
  'comoros': 'KM',
  'congo': 'CG',
  'republic of the congo': 'CG',
  'democratic republic of the congo': 'CD',
  'dr congo': 'CD',
  'drc': 'CD',
  'costa rica': 'CR',
  "cote d'ivoire": 'CI',
  'ivory coast': 'CI',
  'croatia': 'HR',
  'cuba': 'CU',
  'cyprus': 'CY',
  'czech republic': 'CZ',
  'czechia': 'CZ',
  // D
  'denmark': 'DK',
  'djibouti': 'DJ',
  'dominica': 'DM',
  'dominican republic': 'DO',
  // E
  'east timor': 'TL',
  'timor-leste': 'TL',
  'ecuador': 'EC',
  'egypt': 'EG',
  'el salvador': 'SV',
  'equatorial guinea': 'GQ',
  'eritrea': 'ER',
  'estonia': 'EE',
  'eswatini': 'SZ',
  'swaziland': 'SZ',
  'ethiopia': 'ET',
  // F
  'fiji': 'FJ',
  'finland': 'FI',
  'france': 'FR',
  // G
  'gabon': 'GA',
  'gambia': 'GM',
  'the gambia': 'GM',
  'georgia': 'GE',
  'germany': 'DE',
  'ghana': 'GH',
  'greece': 'GR',
  'grenada': 'GD',
  'guatemala': 'GT',
  'guinea': 'GN',
  'guinea-bissau': 'GW',
  'guyana': 'GY',
  // H
  'haiti': 'HT',
  'honduras': 'HN',
  'hong kong': 'HK',
  'hungary': 'HU',
  // I
  'iceland': 'IS',
  'india': 'IN',
  'indonesia': 'ID',
  'iran': 'IR',
  'iraq': 'IQ',
  'ireland': 'IE',
  'israel': 'IL',
  'italy': 'IT',
  // J
  'jamaica': 'JM',
  'japan': 'JP',
  'jordan': 'JO',
  // K
  'kazakhstan': 'KZ',
  'kenya': 'KE',
  'kiribati': 'KI',
  'north korea': 'KP',
  "korea, democratic people's republic of": 'KP',
  'south korea': 'KR',
  'korea': 'KR',
  'korea, republic of': 'KR',
  'republic of korea': 'KR',
  'kuwait': 'KW',
  'kyrgyzstan': 'KG',
  // L
  'laos': 'LA',
  'lao': 'LA',
  "lao people's democratic republic": 'LA',
  'latvia': 'LV',
  'lebanon': 'LB',
  'lesotho': 'LS',
  'liberia': 'LR',
  'libya': 'LY',
  'liechtenstein': 'LI',
  'lithuania': 'LT',
  'luxembourg': 'LU',
  // M
  'macao': 'MO',
  'macau': 'MO',
  'madagascar': 'MG',
  'malawi': 'MW',
  'malaysia': 'MY',
  'maldives': 'MV',
  'mali': 'ML',
  'malta': 'MT',
  'marshall islands': 'MH',
  'mauritania': 'MR',
  'mauritius': 'MU',
  'mexico': 'MX',
  'micronesia': 'FM',
  'moldova': 'MD',
  'monaco': 'MC',
  'mongolia': 'MN',
  'montenegro': 'ME',
  'morocco': 'MA',
  'mozambique': 'MQ',
  'myanmar': 'MM',
  'burma': 'MM',
  // N
  'namibia': 'NA',
  'nauru': 'NR',
  'nepal': 'NP',
  'netherlands': 'NL',
  'the netherlands': 'NL',
  'holland': 'NL',
  'new zealand': 'NZ',
  'nicaragua': 'NI',
  'niger': 'NE',
  'nigeria': 'NG',
  'north macedonia': 'MK',
  'macedonia': 'MK',
  'norway': 'NO',
  // O
  'oman': 'OM',
  // P
  'pakistan': 'PK',
  'palau': 'PW',
  'palestine': 'PS',
  'panama': 'PA',
  'papua new guinea': 'PG',
  'paraguay': 'PY',
  'peru': 'PE',
  'philippines': 'PH',
  'the philippines': 'PH',
  'poland': 'PL',
  'portugal': 'PT',
  'puerto rico': 'PR',
  // Q
  'qatar': 'QA',
  // R
  'romania': 'RO',
  'russia': 'RU',
  'russian federation': 'RU',
  'rwanda': 'RW',
  // S
  'saint kitts and nevis': 'KN',
  'saint lucia': 'LC',
  'saint vincent and the grenadines': 'VC',
  'samoa': 'WS',
  'san marino': 'SM',
  'sao tome and principe': 'ST',
  'saudi arabia': 'SA',
  'senegal': 'SN',
  'serbia': 'RS',
  'seychelles': 'SC',
  'sierra leone': 'SL',
  'singapore': 'SG',
  'slovakia': 'SK',
  'slovenia': 'SI',
  'solomon islands': 'SB',
  'somalia': 'SO',
  'south africa': 'ZA',
  'south sudan': 'SS',
  'spain': 'ES',
  'sri lanka': 'LK',
  'sudan': 'SD',
  'suriname': 'SR',
  'sweden': 'SE',
  'switzerland': 'CH',
  'syria': 'SY',
  'syrian arab republic': 'SY',
  // T
  'taiwan': 'TW',
  'tajikistan': 'TJ',
  'tanzania': 'TZ',
  'thailand': 'TH',
  'togo': 'TG',
  'tonga': 'TO',
  'trinidad and tobago': 'TT',
  'tunisia': 'TN',
  'turkey': 'TR',
  'turkiye': 'TR',
  'turkmenistan': 'TM',
  'tuvalu': 'TV',
  // U
  'uganda': 'UG',
  'ukraine': 'UA',
  'united arab emirates': 'AE',
  'uae': 'AE',
  'united kingdom': 'GB',
  'uk': 'GB',
  'great britain': 'GB',
  'england': 'GB',
  'scotland': 'GB',
  'wales': 'GB',
  'united states': 'US',
  'united states of america': 'US',
  'usa': 'US',
  'us': 'US',
  'america': 'US',
  'uruguay': 'UY',
  'uzbekistan': 'UZ',
  // V
  'vanuatu': 'VU',
  'vatican city': 'VA',
  'venezuela': 'VE',
  'vietnam': 'VN',
  'viet nam': 'VN',
  'việt nam': 'VN',
  // Y
  'yemen': 'YE',
  // Z
  'zambia': 'ZM',
  'zimbabwe': 'ZW',
}

/** Convert an ISO 3166-1 alpha-2 code to a regional indicator emoji flag. */
function isoToEmoji(iso: string): string {
  const codePoints = [...iso.toUpperCase()].map(
    (c) => 0x1f1e6 + c.charCodeAt(0) - 65
  )
  return String.fromCodePoint(...codePoints)
}

/**
 * Convert a country name to its emoji flag.
 * Returns null for unmapped or empty inputs.
 */
export function countryToFlag(countryName: string | null | undefined): string | null {
  if (!countryName?.trim()) return null
  const iso = COUNTRY_TO_ISO[countryName.trim().toLowerCase()]
  if (!iso) return null
  return isoToEmoji(iso)
}
